chore(github): pull request template
americanexpress/react-albus pull request #88
Opened 2021-01-26 13:20 UTC by nellyk

2021-01-26 13:20 UTC, nellyk commented on .github/pull_request_template.md
> +- [ ] This change adds additional environment variable requirements for Holocron users.
```suggestion
- [ ] This change adds additional environment variable requirements for react-albus users.
```

2021-01-26 16:41 UTC, BenMcLees approved these changes

2021-01-28 20:56 UTC, JAdshead requested changes

2021-02-02 12:57 UTC, infoxicator approved these changes

2021-02-02 15:18 UTC, Francois-Esquire approved these changes

2021-02-02 15:54 UTC, JamesSingleton approved these changes

2021-02-03 20:21 UTC, JAdshead approved these changes

2021-02-04 00:26 UTC, merged